#! /bin/sh

. ./lib.sh

rm -rf ${TOPOUTDIR}.old
mv --update ${TOPOUTDIR} ${TOPOUTDIR}.old || true
mkdir ${TOPOUTDIR}

IKS='+'

generate () {
    set -e
    templateName=$1
    shift
    gemp -verbose \
         CodeGenWarning="Code generated by gemp -- DO NOT EDIT." \
         UintSize=64,32,16 "$@" \
         gen -outtopdir ../$TOPOUTDIR -inkeyseparator ${IKS} \
         $templateName

    #    printf "gemp returned status %d\n" "$?"
}

(
    cd _templates
    generate testbits${IKS}UintSize/main_test.go
    generate testbits${IKS}UintSize/loop${IKS}UintOperation${IKS}_test.go \
             UintOperation="Reverse,ReverseBytes"
)

go mod tidy

